Strawman compatibility categories
FamilySearch/GEDCOM.io pull request #41
Opened 2022-05-22 17:39 UTC by dthaler

Signed-off-by: Dave Thaler <dthaler@armidalesoftware.com>

2022-05-22 17:57 UTC, jamestanner45 commented
Looks good to me.


On Sun, May 22, 2022 at 11:40 AM Dave Thaler ***@***.***>
wrote:

> @dthaler <https://github.com/dthaler> requested your review on: #41
> <https://github.com/FamilySearch/GEDCOM.io/pull/41> Strawman
> compatibility categories.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/FamilySearch/GEDCOM.io/pull/41#event-6656440138>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO6Y44FOTW3FYOYOCOGMGWTVLJWPJANCNFSM5WTV5FIQ>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2022-05-22 19:36 UTC, albertemmerich commented
For Tree Compatibility level 2 we should have 
`<<EVENT_DETAIL>>.NOTE`

2022-05-22 19:37 UTC, albertemmerich commented
Will there be a compatibility level 3, with full spec covered?

2022-05-22 23:35 UTC, dthaler commented
> For Tree Compatibility level 2 we should have `<<EVENT_DETAIL>>.NOTE`

Agree, added.

2022-05-24 20:30 UTC, tychonievich commented
I think we are missing some important components. 

- There ought to be some styling compatibility (NOTE.MIME, SOUR.TEXT.MIME, other MIME if SNOTE and SNOTE.TRAN supported)
- There should be a logging compatibility that always sets CREA and CHAN dates appropriately
- There should be an extension compatibility that can retag conflicting documented extension tags upon import and present relocated standard structures in the user interface
- There should be at least one "full compatibility" level, and probably two:
   - One that lets users read, modify, and create any standards-compliant file
   - One that lets users read any standards-compliant file but may omit tools to create some (e.g. not permitting duplicate data, moving single-use SNOTE to NOTE, limiting ALIA use to particular situations, normalizing name parts, enforcing recommendations as well as requirements, etc.)

I do not support publishing this unless a full compatibility level is included; otherwise it looks like we are saying "most of the standard doesn't matter."

2022-05-24 20:30 UTC, tychonievich requested changes

2022-05-24 20:30 UTC, tychonievich commented on _pages/compatibility.md
> +> The vendor only needs to demonstrate the ability to read the [maximal70.ged](..\testfiles\gedcom70\maximal70.ged) file and display the contents in their own environment.
```suggestion
> The vendor only needs to demonstrate the ability to read the [maximal70.ged](../testfiles/gedcom70/maximal70.ged) file and display the contents in their own environment.
```

2022-05-24 21:15 UTC, tychonievich requested changes
Some typos and wording changes

2022-05-24 21:15 UTC, tychonievich commented on _pages/compatibility.md
> +> The vendor only needs to demonstrate the ability to read the [maximal70.ged](../testfiles/gedcom70/maximal70.ged) file and display the contents in their own environment.
```suggestion
> The vendor needs to demonstrate the ability to read the [maximal70.ged](../testfiles/gedcom70/maximal70.ged) file and display the contents in their own environment.
```

2022-05-24 21:15 UTC, tychonievich commented on _pages/compatibility.md
> +> The vendor only needs to demonstrate the ability to write a sample FamilySearch GEDCOM file and prove that it is valid FamilySearch GEDCOM 7. For example, the [GEDCOM validator](http://ged-inline.e
```suggestion
> The vendor needs to demonstrate the ability to write a sample FamilySearch GEDCOM file and prove that it is valid FamilySearch GEDCOM 7. For example, the [GEDCOM validator](http://ged-inline.elasticbeanstalk.com/) can be used, although it is still in beta.
```

2022-05-24 21:15 UTC, tychonievich commented on _pages/compatibility.md
> +> The vendor only needs to demonstrate the ability to write a sample FamilySearch GEDCOM file and prove that it is valid FamilySearch GEDCOM 7. For example, the [GEDCOM validator](http://ged-inline.e
```suggestion
> The vendor only needs to demonstrate the ability to write a sample FamilySearch GEDCOM 7 file and that any FamilySearch GEDCOM 7 files they write are conformant with the FamilySearch GEDCOM 7 specification. For example, the [GEDCOM validator](http://ged-inline.elasticbeanstalk.com/) can be used to check validity, although it is still in beta.
```

2022-05-25 07:22 UTC, albertemmerich commented
There are applications which import anything and let at export all parts unmodified they do not understand. These applications would get a very high score if we only test import of compliant files and then export.
Should we add a test for the reaction of applications, if they import a file which is not compliant? If they do not react and do not eliminate any deviations to standard rules, they cannot be called compatibel: They export the deviations and by that break the standard rules.

2022-05-25 16:29 UTC, dthaler commented
> There are applications which import anything and let at export all parts unmodified they do not understand. These applications would get a very high score if we only test import of compliant files and then export. Should we add a test for the reaction of applications, if they import a file which is not compliant? If they do not react and do not eliminate any deviations to standard rules, they cannot be called compatibel: They export the deviations and by that break the standard rules.

Agree.  We had this under Write but not Read/Write.  I've now added it there too for consistency.

2022-05-31 21:07 UTC, tychonievich commented
At a high level, ignoring the specific tags supported, I think we have:

**Write-compliant**:
Any 7.0 file exported by the application is valid GEDCOM

**Read-compliant**:
Imposes no import limitations not present in the GEDCOM specification

**Delta-compliant**:
An import-modify-export introduces no new errors beyond those present in the imported file

2022-05-31 21:12 UTC, dthaler commented
Albert reports that John Cardinal has an invalid file (assess.ged) at https://gedcomassessment.com/en/index.htm that may be useful for applications wanting to test with an invalid GEDCOM 5.5.1 file.

2022-05-31 21:19 UTC, tychonievich approved these changes

2022-05-31 21:21 UTC, merged

2022-10-11 09:15 UTC, jamestanner45 commented
Albert is right. I agree. Garbage in garbage out.

James

On Wed, May 25, 2022 at 1:23 AM Albert Emmerich ***@***.***>
wrote:

> There are applications which import anything and let at export all parts
> unmodified they do not understand. These applications would get a very high
> score if we only test import of compliant files and then export.
> Should we add a test for the reaction of applications, if they import a
> file which is not compliant? If they do not react and do not eliminate any
> deviations to standard rules, they cannot be called compatibel: They export
> the deviations and by that break the standard rules.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/FamilySearch/GEDCOM.io/pull/41#issuecomment-1136883578>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO6Y44FKMYSMAUC3AV3QUVLVLXINPANCNFSM5WTV5FIQ>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>